import { DROP_ITEMS, DROP_CHANCE } from '../data/dropItems.js'
import { DropItem } from '../entities/DropItem.js'
import { ExpDrop } from '../entities/Projectile.js'

export class DropSystem {
  spawnFromKill(x, y) {
    if (Math.random() > DROP_CHANCE) return null
    const type = DROP_ITEMS[Math.floor(Math.random() * DROP_ITEMS.length)]
    return new DropItem(x, y, type)
  }

  // Returns additional ExpDrops generated by Bomb chain
  applyPickup(dropItem, player, enemies, expDrops, onExpGain) {
    const id = dropItem.type.id

    if (id === 'meat') {
      player.hp = Math.min(player.hp + player.maxHp * 0.3, player.maxHp)
    } else if (id === 'magnet') {
      let total = 0
      for (const d of expDrops) {
        if (!d.dead) { total += d.value; d.dead = true }
      }
      if (total > 0) onExpGain(total)
    } else if (id === 'bomb') {
      const newDrops = []
      for (const e of enemies) {
        if (e.dead) continue
        const wasAlive = true
        e.takeDamage(999999)
        if (wasAlive && e.dead) {
          // exp drop
          expDrops.push(new ExpDrop(e.x, e.y, e.exp))
          // 1-level chain drop (no further chain)
          const chainDrop = this.spawnFromKill(e.x, e.y)
          if (chainDrop) newDrops.push(chainDrop)
        }
      }
      return newDrops
    }
    return []
  }
}
